name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2 # Caches compiled dependencies between runs
      - run: cargo check # Checks that the code compiles without actually running it
      - run: cargo test # Runs the tests
      - run: cargo fmt -- --check # Checks that the code is formatted according to rustfmt
      - run: cargo clippy -- -D warnings # Runs Clippy and treats all warnings as errors
